baseURL = "https://swlee3306.github.io/sulee_portfolio/"
languageCode = "ko-kr"
title = "Dev Note by sw'Lee"
# 테마를 사용하지 않고 커스텀 레이아웃을 사용합니다.
# theme = ""

# GitHub Pages 프로젝트 사이트 호환을 위해 상대/정규화 URL 활성화
relativeURLs = true
canonifyURLs = true

[pagination]
  pagerSize = 10

[params]
  author = "이상욱"
  description = "개인 포트폴리오"
  ogImage = "/images/og-default.svg"
  email = "swlee3306@gmail.com"
  useWebp = true # .webp가 존재할 때만 <picture> 사용, 없으면 원본으로 폴백
  brand = "Dev Note by sw'Lee"
  [params.analytics]
    ga4 = ""           # 예: G-XXXXXXX
    plausibleDomain = "" # 예: yourdomain.com
  socials = [
    { name = "GitHub", url = "https://github.com/swlee3306" },
    { name = "LinkedIn", url = "https://www.linkedin.com/" },
    { name = "Email", url = "mailto:swlee3306@gmail.com" }
  ]

[outputs]
  home = ["HTML", "RSS", "RobotsTXT"]

[outputFormats]
  [outputFormats.RobotsTXT]
    mediaType = "text/plain"
    baseName = "robots"
    isPlainText = true
    notAlternative = true

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
